import "./../globals.css";
import { Poppins } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const p = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "MeroByapar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={p.className}>
        <main className="flex sm:gap-6 max-h-screen  overflow-hidden">
          <Sidebar />
          <div className="pt-20 sm:pt-6 overflow-y-scroll overflow-x-hidden sm:overflow-x-auto grow pr-8 pb-20">
            {" "}
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
