import React from "react";
import "./globals.css";
import { Poppins } from "next/font/google";
import ReactQueryProvider from "@/components/ReactQueryProvider";
const p = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "MeroByapar",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body className={p.className}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
