export const productRows = [
  {
    Index: 1,
    Name: "Product 1",
    Code: "ABC123",
    Quantity: 10,
    Price: 20.99,
    "Bought Date": "2023-05-15",
    "Bought By": "John",
  },
  {
    Index: 2,
    Name: "Product 2",
    Code: "DEF456",
    Quantity: 5,
    Price: 10.99,
    "Bought Date": "2023-05-18",
    "Bought By": "Jane",
  },
  {
    Index: 3,
    Name: "Product 3",
    Code: "GHI789",
    Quantity: 8,
    Price: 15.99,
    "Bought Date": "2023-05-20",
    "Bought By": "Sarah",
  },
  {
    Index: 4,
    Name: "Product 4",
    Code: "JKL012",
    Quantity: 2,
    Price: 5.99,
    "Bought Date": "2023-05-22",
    "Bought By": "Michael",
  },
  {
    Index: 5,
    Name: "Product 5",
    Code: "MNO345",
    Quantity: 15,
    Price: 25.99,
    "Bought Date": "2023-05-25",
    "Bought By": "David",
  },
];

export const categoryRows = [
  {
    Index: 1,
    Name: "Category 1",
    Code: "CAT001",
    "Total Products": 10,
    Actions: "View",
  },
  {
    Index: 2,
    Name: "Category 2",
    Code: "CAT002",
    "Total Products": 5,
    Actions: "View",
  },
  {
    Index: 3,
    Name: "Category 3",
    Code: "CAT003",
    "Total Products": 8,
    Actions: "View",
  },
  {
    Index: 4,
    Name: "Category 4",
    Code: "CAT004",
    "Total Products": 2,
    Actions: "View",
  },
  {
    Index: 5,
    Name: "Category 5",
    Code: "CAT005",
    "Total Products": 15,
    Actions: "View",
  },
];

export const toBuyItemArray = [
  {
    Index: 1,
    Name: "Item 1",
    Category: "Category 1",
    "Min quantity": 5,
    "Deadline to buy": "2023-06-10",
    Actions: "Edit / Delete",
  },
  {
    Index: 2,
    Name: "Item 2",
    Category: "Category 2",
    "Min quantity": 10,
    "Deadline to buy": "2023-06-15",
    Actions: "Edit / Delete",
  },
  {
    Index: 3,
    Name: "Item 3",
    Category: "Category 1",
    "Min quantity": 3,
    "Deadline to buy": "2023-06-12",
    Actions: "Edit / Delete",
  },
  {
    Index: 4,
    Name: "Item 4",
    Category: "Category 3",
    "Min quantity": 8,
    "Deadline to buy": "2023-06-18",
    Actions: "Edit / Delete",
  },
  {
    Index: 5,
    Name: "Item 5",
    Category: "Category 2",
    "Min quantity": 6,
    "Deadline to buy": "2023-06-14",
    Actions: "Edit / Delete",
  },
];
export const salesArray = [
  {
    Index: 1,
    "Product Name": "Product 1",
    Code: "ABC123",
    Quantity: 10,
    "Cost Price": 10.99,
    "Sold Price": 19.99,
    "Sold Date": "2023-06-01",
    "Sold By": "John",
    Actions: "Edit / Delete",
  },
  {
    Index: 2,
    "Product Name": "Product 2",
    Code: "DEF456",
    Quantity: 5,
    "Cost Price": 7.99,
    "Sold Price": 14.99,
    "Sold Date": "2023-06-03",
    "Sold By": "Jane",
    Actions: "Edit / Delete",
  },
  {
    Index: 3,
    "Product Name": "Product 3",
    Code: "GHI789",
    Quantity: 8,
    "Cost Price": 12.99,
    "Sold Price": 24.99,
    "Sold Date": "2023-06-05",
    "Sold By": "Sarah",
    Actions: "Edit / Delete",
  },
  {
    Index: 4,
    "Product Name": "Product 4",
    Code: "JKL012",
    Quantity: 2,
    "Cost Price": 5.99,
    "Sold Price": 11.99,
    "Sold Date": "2023-06-07",
    "Sold By": "Michael",
    Actions: "Edit / Delete",
  },
  {
    Index: 5,
    "Product Name": "Product 5",
    Code: "MNO345",
    Quantity: 15,
    "Cost Price": 18.99,
    "Sold Price": 29.99,
    "Sold Date": "2023-06-09",
    "Sold By": "David",
    Actions: "Edit / Delete",
  },
];
export const employeesArray = [
  {
    Index: 1,
    Name: "John Doe",
    Email: "johndoe@example.com",
    Contact: "1234567890",
    "Joined Date": "2023-06-01",
    Position: "Manager",
    Actions: "Edit / Delete",
  },
  {
    Index: 2,
    Name: "Jane Smith",
    Email: "janesmith@example.com",
    Contact: "9876543210",
    "Joined Date": "2023-06-03",
    Position: "Supervisor",
    Actions: "Edit / Delete",
  },
  {
    Index: 3,
    Name: "Sarah Johnson",
    Email: "sarahjohnson@example.com",
    Contact: "4567891230",
    "Joined Date": "2023-06-05",
    Position: "Assistant",
    Actions: "Edit / Delete",
  },
  {
    Index: 4,
    Name: "Michael Brown",
    Email: "michaelbrown@example.com",
    Contact: "7891234560",
    "Joined Date": "2023-06-07",
    Position: "Associate",
    Actions: "Edit / Delete",
  },
  {
    Index: 5,
    Name: "David Wilson",
    Email: "davidwilson@example.com",
    Contact: "3216549870",
    "Joined Date": "2023-06-09",
    Position: "Intern",
    Actions: "Edit / Delete",
  },
];